version: '3.4'

services:
  developerapi:
    image: ${DOCKER_REGISTRY-}developerapi
    build:
      context: .
      dockerfile: Services/Developer.API/Dockerfile

  postsapi:
    image: ${DOCKER_REGISTRY-}postsapi
    build:
      context: .
      dockerfile: Services/Posts.API/Dockerfile

  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
