version: '3.4'

services:
  developerapi:
    container_name: developerapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - "8003:80"

  postsapi:
    container_name: postsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - "8002:80"

  gatewayapi:
    container_name: gatewayapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - "8001:80"

  webapp:
    container_name: webapp
    environment:
        - ASPNETCORE_ENVIRONMENT=Release
    ports:
        - "8000:80"
        